import { createRoot } from 'react-dom/client'
import './service-newsletter.css'
import logoDark from '../8.png'

const website = 'https://acdhcreatives.vercel.app/'
const contact = `${website}#contact`

export function ServiceNewsletter({ config }) {
  return (
    <main className="service-newsletter" style={{ '--accent': config.accent, '--accent-soft': config.soft }}>
      <header className="service-nav"><a href={website}><img src={logoDark} alt="ACDH Creatives" /></a><span>{config.label} / {config.number}</span><a href={contact}>{config.cta} <b>+</b></a></header>
      <section className="service-hero"><div className="service-hero-copy"><p className="eyebrow"><i /> ACDH CREATIVES / {config.kicker}</p><p className="hero-index">01 / 10</p><h1>{config.hero[0]}<br /><em>{config.hero[1]}</em></h1><p className="lead">{config.lead}</p><p className="muted">{config.intro}</p><a className="service-button" href={contact}>{config.cta} <span>-&gt;</span></a></div><div className="service-hero-visual"><div className="visual-glow" /><img src={config.image} alt={`${config.title} sample`} /><span className="visual-label">ACDH / {config.label}</span></div></section>
      <div className="service-marquee">{config.marquee.map((item, index) => <span key={`${item}-${index}`}>{item} <b>*</b></span>)}</div>
      <section className="service-section problem-section"><div className="section-number">02 / THE PROBLEM</div><div><h2>{config.problemTitle[0]}<br /><em>{config.problemTitle[1]}</em></h2><p className="muted section-intro">{config.problemIntro}</p><div className="problem-grid">{config.problems.map((item) => <div key={item}><b>x</b><span>{item}</span></div>)}</div><div className="result-line"><span>The result?</span><strong>{config.result}</strong></div></div></section>
      <section className="solution-section"><p className="eyebrow"><i /> 03 / THE SOLUTION</p><h2>{config.solutionTitle[0]}<br /><em>{config.solutionTitle[1]}</em></h2><p>{config.solution}</p><strong className="solution-statement">{config.statement[0]}<br />{config.statement[1]}</strong></section>
      <section className="service-section included-section"><div className="section-number">04 / WHAT IS INCLUDED</div><div><p className="eyebrow"><i /> {config.label} system</p><h2>{config.includedTitle[0]}<br /><em>{config.includedTitle[1]}</em></h2><div className="included-grid">{config.included.map(([number, title, text, items]) => <article key={number}><span className="card-number">{number}</span><h3>{title}</h3><p>{text}</p><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>
      <section className="journey-section"><div className="section-number">05 / YOUR {config.journeyLabel.toUpperCase()}</div><div><p className="eyebrow"><i /> {config.journeyEyebrow}</p><h2>{config.journeyTitle[0]}<br /><em>{config.journeyTitle[1]}</em></h2><div className="journey-list">{config.journey.map(([number, title, text], index) => <div key={number} className="journey-step"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div>{index < config.journey.length - 1 && <b>↓</b>}</div>)}</div></div></section>
      <section className="package-section service-section"><div className="section-number">06 / PACKAGE SECTION</div><div><p className="eyebrow"><i /> Choose your {config.packageLabel}</p><h2>{config.packageTitle[0]}<br /><em>{config.packageTitle[1]}</em></h2><div className="package-table"><div className="package-head"><span>Package</span><span>Price</span><span>Best for</span></div>{config.packages.map((pkg) => <div key={pkg.name} className={pkg.featured ? 'package-pro' : ''}><strong>{pkg.name}{pkg.featured && <em>Priority</em>}</strong><b>{pkg.price}</b><span>{pkg.best}</span></div>)}</div><div className="package-cards">{config.packages.map((pkg) => <article className={pkg.featured ? 'pro-card' : ''} key={pkg.name}><h3>{pkg.name}{pkg.featured && <em>Priority</em>}</h3><strong>{pkg.price}</strong><p>{pkg.description}</p><b>Includes</b><p>{pkg.includes.join(' / ')}</p></article>)}</div></div></section>
      <section className="before-after-section"><div className="section-number">07 / BEFORE / AFTER</div><div><p className="eyebrow"><i /> The difference is in the system</p><h2>{config.compareTitle[0]}<br /><em>{config.compareTitle[1]}</em></h2><div className="comparison"><article><span>Before</span><h3>{config.beforeAfter[0].title}</h3>{config.beforeAfter[0].items.map((item) => <p key={item}>{item}</p>)}<b>↓</b></article><article className="after-card"><span>After</span><h3>{config.beforeAfter[1].title}</h3>{config.beforeAfter[1].items.map((item) => <p key={item}>{item}</p>)}</article></div><strong className="comparison-footer">{config.compareFooter}</strong></div></section>
      <section className="reasons-section service-section"><div className="section-number">08 / WHY {config.label.toUpperCase()}</div><div><p className="eyebrow"><i /> A stronger {config.reasonSubject} helps you</p><h2>{config.reasonsTitle[0]}<br /><em>{config.reasonsTitle[1]}</em></h2><div className="reason-list">{config.reasons.map(([title, text], index) => <div key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section className="approach-section"><p className="eyebrow"><i /> 09 / THE ACDH APPROACH</p><h2>{config.approachTitle[0]}<br /><em>{config.approachTitle[1]}</em></h2><p>{config.approach}</p><strong>{config.process.map((item, index) => <span key={item}>{index > 0 && <> <i>-&gt;</i> </>}{item}</span>)}</strong></section>
      <section className="launch-section"><div className="launch-mark">*</div><p className="eyebrow">10 / START YOUR {config.label.toUpperCase()}</p><h2>Ready to make<br /><em>an impact?</em></h2><p className="muted">{config.launch}</p><a className="service-button" href={contact}>{config.cta} <span>-&gt;</span></a><p className="launch-note">Replies available every day / Batangas, PH</p></section>
      <footer className="service-footer"><img src={logoDark} alt="ACDH Creatives" /><p className="eyebrow">INNOVATION THROUGH INSIGHT</p><h2>Make your work<br /><em>easy to remember.</em></h2><p className="muted">ACDH Creatives helps growing businesses turn ideas into useful branding, marketing and digital systems.</p><strong>Branding / Marketing / Design / Digital</strong><a className="service-button" href={contact}>{config.cta} <span>-&gt;</span></a></footer>
    </main>
  )
}

export function renderServiceNewsletter(config) {
  createRoot(document.getElementById('service-newsletter-root')).render(<ServiceNewsletter config={config} />)
}
